(kicad_sch (version 20211014) (generator ps2561_single_channel)
  (paper "A4")
  (symbol "Device:PS2561" (lib_id "PS2561:PS2561") (at 50 200) (unit 1)
    (property "Reference" "U1" (id 1) (at 0 0) (effects (font (size 1 1))))
    (property "Value" "PS2561" (id 2) (at 0 -2) (effects (font (size 1 1))))
    (pin 1  "LED_A"   (at -2 2) (type passive) (number 1))
    (pin 2  "LED_K"   (at -2 -2) (type passive) (number 2))
    (pin 3  "C"       (at 2 2) (type passive) (number 3))
    (pin 4  "E"       (at 2 -2) (type passive) (number 4))
  )

  (symbol "Device:R" (lib_id "Device:R") (at 20 180)
    (property "Reference" "R1" (id 1))
    (property "Value" "12k" (id 2))
    (pin 1 "1" (at -1 0) (type passive) (number 1))
    (pin 2 "2" (at 1 0) (type passive) (number 2))
  )

  (symbol "Device:R" (lib_id "Device:R") (at 80 180)
    (property "Reference" "R2" (id 1))
    (property "Value" "10k" (id 2))
    (pin 1 "1" (at -1 0) (type passive) (number 1))
    (pin 2 "2" (at 1 0) (type passive) (number 2))
  )

  (symbol "Device:C" (lib_id "Device:C") (at 80 210)
    (property "Reference" "C1" (id 1))
    (property "Value" "10nF" (id 2))
    (pin 1 "1" (at -1 0) (type passive) (number 1))
    (pin 2 "2" (at 1 0) (type passive) (number 2))
  )

  ;; Output direct opto (B1)
  (symbol "Device:R" (lib_id "Device:R") (at 220 180)
    (property "Reference" "R3" (id 1))
    (property "Value" "750" (id 2))
    (pin 1 "1" (at -1 0) (type passive) (number 1))
    (pin 2 "2" (at 1 0) (type passive) (number 2))
  )

  (symbol "Device:LOAD" (lib_id "Device:Load") (at 260 180)
    (property "Reference" "LOAD1" (id 1))
    (property "Value" "LOAD" (id 2))
    (pin 1 "+" (at -1 0) (type passive) (number 1))
    (pin 2 "-" (at 1 0) (type passive) (number 2))
  )

  ;; Output via PNP (B2)
  (symbol "Device:Q_PNP" (lib_id "Device:Q_PNP") (at 420 180)
    (property "Reference" "Q1" (id 1))
    (property "Value" "BC327" (id 2))
    (pin 1 "E" (at -1 2) (type passive) (number 1))
    (pin 2 "B" (at 0 0) (type passive) (number 2))
    (pin 3 "C" (at 1 -2) (type passive) (number 3))
  )

  (symbol "Device:R" (lib_id "Device:R") (at 360 160)
    (property "Reference" "R4" (id 1))
    (property "Value" "4.7k" (id 2))
    (pin 1 "1" (at -1 0) (type passive) (number 1))
    (pin 2 "2" (at 1 0) (type passive) (number 2))
  )

  (symbol "Device:R" (lib_id "Device:R") (at 420 220)
    (property "Reference" "R5" (id 1))
    (property "Value" "750" (id 2))
    (pin 1 "1" (at -1 0) (type passive) (number 1))
    (pin 2 "2" (at 1 0) (type passive) (number 2))
  )

  (symbol "Device:C" (lib_id "Device:C") (at 440 140)
    (property "Reference" "C2" (id 1))
    (property "Value" "0.1uF" (id 2))
    (pin 1 "1" (at -1 0) (type passive) (number 1))
    (pin 2 "2" (at 1 0) (type passive) (number 2))
  )

  ;; Power rails and net labels
  (footprint "PowerFlag" (at 10 20) (value "24V"))
  (footprint "PowerFlag" (at 10 260) (value "GND"))
  (footprint "PowerFlag" (at 140 20) (value "5V"))

  ;; Nets (textual mapping for user's clarity)
  (net "24V" (node (xy 10 30)))
  (net "GND" (node (xy 10 250)))
  (net "MCU_5V" (node (xy 140 30)))

  ;; Simple connection notes
  (label (at 30 170) (text "A) Input: PS2561 invert"))
  (label (at 240 170) (text "B1) Output: direct opto (low current)"))
  (label (at 420 170) (text "B2) Output: opto -> PNP (50mA)") )
)
